spring.application.name=studyflow
spring.datasource.url=jdbc:h2:mem:studyflowdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=spring
spring.datasource.password=2020
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true
spring.h2.console.path=/h2-consol

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true